//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbConection
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicio()
        {
            this.turnos = new HashSet<turno>();
        }
    
        public int id_servicio { get; set; }
        public int id_comercio { get; set; }
        public string nom_servicio { get; set; }
        public System.TimeSpan hora_apertura { get; set; }
        public System.TimeSpan hora_cierre { get; set; }
        public short duracion { get; set; }
    
        public virtual comercio comercio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turno> turnos { get; set; }
    }
}
